version: "3"

services:
  node:
    image: "node:14"
    user: "node"
    working_dir: /home/node/app
    volumes:
    - ./:/home/node/app
    command: "node build/index.js"
    environment:
      # API Self
      API_URL: "https://api.example.com"

      # Developer Settings
      APIDOC: "true"

      #PWA
      PWA_URL: "https://pwa.example.com"

      #Notifications

      ##Telegram
      TELEGRAM: "true"
      TELEGRAM_KEY: "TelegramKey"
      TELEGRAM_VALIDATION_URL: "VALIDATION_URL"

      # FCM
      FCM: "false"
      FCM_URL: "https://url_server.firebaseio.com"
      FCM_CREDENTIALS: "/home/node/app/keys/fcm_key.json"

      # WebPush
      WEBPUSH: "false"
      VAPID_PUBLIC: "YOUR_VAPID_PUBIC"
      VAPID_PRIVATE: "YOUR_VAPID_PRIVATE"
      VAPID_SUBJECT: "YOUR_VAPID_SUBJECT"

      # Sendgrid
      SENDGRID: "true"
      SENDGRID_KEY: "SG.BEARER_TOKEN"
      SENDGRID_HOST: "YOUT_SG_HOST"
      SENDGRID_PW_VALIDATION_URL: "SG_VALIDATION_HOST"

      # LDAP
      LDAP: "true"

      LDAP_HOST: "ldap://127.0.0.1:389"
      LDAP_ROOT: "DC=example,DC=com"
      LDAP_DOMAIN: "example"

      LDAP_STUDENTSGROUP: "CN=Students,DC=example,DC=com"
      LDAP_TEACHERGROUP: "CN=Teacher,DC=example,DC=com"

      LDAP_USER: "user"
      LDAP_PASS: "password"

      LDAP_TLS: "false"
      LDAP_CA_PATH: "/home/node/app/keys/ldap-ca.pem"

      # MySQL
      SQL_PORT: 3306
      SQL_HOST: "mysql"
      SQL_USER: "splan"
      SQL_PASS: "pass"
      SQL_DB: "splan"

      # Moodle
      MOODLE: "false"
      MOODLE_URL: "https://moodleServer.example.de/webservice/rest/server.php"
      MOODLE_KEY: "MOODLE_KEY"

    expose:
      - 3000
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
      MYSQL_USER: "splan"
      MYSQL_PASSWORD: "splan"
      MYSQL_DATABASE: "splan"
    ports:
      - 3306:3306
    volumes:
      - ./data/database:/var/lib/mysql